export const REQUEST_VAT_RETURN = 'REQUEST_VAT_RETURN';

export const RECEIVE_VAT_RETURN = 'RECEIVE_VAT_RETURN';

export const POST_VAT_RETURN = 'POST_VAT_RETURN';

export const RECEIVE_VAT_RETURN_RECEIPT = 'RECEIVE_VAT_RETURN_RECEIPT';

export const REQUEST_OBLIGATIONS = 'REQUEST_OBLIGATIONS';

export const RECEIVE_OBLIGATIONS = 'RECEIVE_OBLIGATIONS';

export const FETCH_ERROR = 'FETCH_ERROR';

export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
