Description: Tax
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  appRoot:
    Type: String
    Description: app root
  proxyRoot:
    Type: String
    Description: proxy root
  authorityUri:
    Type: String
    Description: OIDC authority uri
  environmentSuffix:
    Type: String
    AllowedValues:
      - ''
      - -int
      - -sys
    Description: Environment suffix e.g -int -sys
  TestClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of test cluster
    Default: TestClusterName
  ProductionClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of production cluster
    Default: ProductionClusterName

Conditions:
  isTesting: !Or
    - !Equals [!Ref environmentSuffix, "-int"]
    - !Equals [!Ref environmentSuffix, "-sys"]

Resources:
  taxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: [ "ecs-tasks.amazonaws.com" ]
            Action: [ "sts:AssumeRole" ]
      Path: "/"
      Policies:
      - PolicyName: taxServices
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            Resource:
              Fn::ImportValue: logging-queue-arn
      - PolicyName: kms
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
            Resource: "*"
      - PolicyName: s3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource: !Sub "arn:aws:s3:::auth${environmentSuffix}*-keysbucket*"
  taxTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt taxRole.Arn
      ContainerDefinitions:
      - Name: tax
        Cpu: '1'
        Essential: 'true'
        Image: !Sub docker.io/linn/tax:${dockerTag}
        PortMappings:
        - ContainerPort: 5050
        Memory: '150'
        LogConfiguration:
          LogDriver: gelf
          Options:
            'gelf-address': 'udp://syslog.linn.co.uk:12201'
            'tag': !Sub tax-${dockerTag}-ecs-task
        Environment:
        - Name: APP_ROOT
          Value: !Ref appRoot
        - Name: PROXY_ROOT
          Value: !Ref proxyRoot
        - Name: AUTHORITY_URIpr
          Value: !Ref authorityUri
        - Name: LOG_AMAZON_SQSQUEUEURI
          Value: !ImportValue logging-queue-url
        - Name: awsRegion
          Value: !Ref AWS::Region
        - Name: KEYS_BUCKET_NAME
          Value:
            Fn::ImportValue:
              !Sub "linn-keys-bucket${environmentSuffix}"
        - Name: KMS_KEY_ALIAS
          Value:
            Fn::ImportValue:
              !Sub "kms-key-alias${environmentSuffix}"
  productionService:
    Type: AWS::ECS::Service
    Properties:
      # Have to use long form conditional
      Cluster: !If
        - isTesting
        - !Sub ${TestClusterName}
        - !Sub ${ProductionClusterName}
      DesiredCount: !If [ isTesting, 1, 2]
      PlacementStrategies:
        - Field: attribute:ecs.availability-zonelogging
          Type: spread
        - Field: instanceId
          Type: spread
      TaskDefinition: !Ref taxTaskDefinition
      Role: ecsServiceRole
      LoadBalancers:
      - ContainerName: tax
        ContainerPort: 5050
        TargetGroupArn:
          Fn::ImportValue:
            !Sub "tax-target-group-arn${environmentSuffix}"
